// const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
// const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
// const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// const actionTypes = {
//     OPEN_SIDEBAR,
//     CLOSE_SIDEBAR,
//     TOGGLE_SIDEBAR
// }

// export default actionTypes;

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const GET_USRE_INFO = 'GET_USRE_INFO'
const TOGGLE_FROM_GROUP = 'TOGGLE_FROM_GROUP'

const GET_USRE_INFO_REUEST = 'GET_USRE_INFO_REUEST'
const GET_USRE_INFO_SUCCESS = 'GET_USRE_INFO_SUCCESS'
const GET_USRE_INFO_FAIL = 'GET_USRE_INFO_FAIL'

const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST'
const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL'

const GET_LIST_GROUP_REUEST = 'GET_LIST_GROUP_REUEST'
const GET_LIST_GROUP_SUCCESS = 'GET_LIST_GROUP_SUCCESS'
const GET_LIST_GROUP_FAIL = 'GET_LIST_GROUP_FAIL'

const REGISTER_USER_REUEST = 'REGISTER_USER_REUEST'
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

const UPDATE_GROUP_REUEST = 'UPDATE_GROUP_REUEST'
const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
const UPDATE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

const DELETE_GROUP_REUEST = 'UPDATE_GROUP_REUEST'
const DELETE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS'
const DELETE_GROUP_FAIL = 'UPDATE_GROUP_FAIL'

const CREATE_GROUP_REUEST = 'UPDATE_GROUP_REUEST'
const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS'
const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL'

const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
const SIGNIN_FAIL = 'SIGNIN_FAIL'

const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export default{
    TOGGLE_SIDEBAR,
    GET_USRE_INFO,
    TOGGLE_FROM_GROUP,

    GET_USRE_INFO_REUEST,
    GET_USRE_INFO_SUCCESS,
    GET_USRE_INFO_FAIL,

    UPDATE_USER_INFO_REQUEST,
    UPDATE_USER_INFO_SUCCESS,
    UPDATE_USER_INFO_FAIL,

    GET_LIST_GROUP_REUEST,
    GET_LIST_GROUP_SUCCESS,
    GET_LIST_GROUP_FAIL,

    REGISTER_USER_REUEST,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAIL,

    UPDATE_GROUP_REUEST,
    UPDATE_GROUP_SUCCESS,
    UPDATE_GROUP_FAIL,

    CREATE_GROUP_REUEST,
    CREATE_GROUP_SUCCESS,
    CREATE_GROUP_FAIL,

    DELETE_GROUP_REUEST,
    DELETE_GROUP_SUCCESS,
    DELETE_GROUP_FAIL,

    SIGNIN_REQUEST,
    SIGNIN_SUCCESS,
    SIGNIN_FAIL,

    CHANGE_PASSWORD_REQUEST,
    CHANGE_PASSWORD_SUCCESS,     
    CHANGE_PASSWORD_FAIL
}